// actions/types.js
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const FETCH_DATA_2_REQUEST = 'FETCH_DATA_2_REQUEST';
export const FETCH_DATA_2_SUCCESS = 'FETCH_DATA_2_SUCCESS';
export const FETCH_DATA_2_FAILURE = 'FETCH_DATA_2_FAILURE';

export const FETCH_DATA_3_REQUEST = 'FETCH_DATA_3_REQUEST';
export const FETCH_DATA_3_SUCCESS = 'FETCH_DATA_3_SUCCESS';
export const FETCH_DATA_3_FAILURE = 'FETCH_DATA_3_FAILURE';

export const FETCH_DATA_4_REQUEST = 'FETCH_DATA_4_REQUEST';
export const FETCH_DATA_4_SUCCESS = 'FETCH_DATA_4_SUCCESS';
export const FETCH_DATA_4_FAILURE = 'FETCH_DATA_4_FAILURE';